# @url = http://localhost:3000
@url = https://backendpeliculas.herokuapp.com

###

GET {{url}}/
###

GET {{url}}/peliculas

###

POST {{url}}/usuarios/registro/
Content-Type: application/json

{
    "email": "rosamari.sab@gmail.com",
    "password": "1234"
}

###
# @name resLogin
POST {{url}}/usuarios/login/
Content-Type: application/json

{
    "email": "rosamari.sab@gmail.com",
    "password": "1234"
}
###
@token = {{resLogin.response.body.encontrado.token}}

POST {{url}}/usuarios/logout/
Content-Type: application/json
Authorization: {{token}}

{
    "email": "rosamari.sab@gmail.com",
    "password": "1234"
}
###

POST {{url}}/usuarios/delete/
Content-Type: application/json
Authorization: {{token}}

{
    "email": "rosamari.sab@gmail.com"
}
###

POST {{url}}/peliculas/add/
Content-Type: application/json

{
    "original_title": "Mulán",
    "description": "El emperador de China emite un decreto para reclutar a un varón por cada familia que deberá servir en el ejército imperial para defender al país de los invasores del norte. Hua Mulán, hija única de un condecorado guerrero, se presenta para evitar que su anciano padre sea llamado a filas. Se hace pasar por un hombre, Hua Jun y se somete a todo tipo de pruebas. Para conseguirlo deberá apelar a su fuerza interior y sacar a la luz todo su potencial. Se trata de una aventura épica que la transformará en una guerrera laureada que la hará merecedora del respeto de todo un país y motivo de orgullo para su padre.",
    "backdrop_path": "/zzWGRw277MNoCs3zhyG3YmYQsXv.jpg"
}
###

POST {{url}}/peliculas/add/
Content-Type: application/json

{
    "original_title": "PELICULA EJEMPLO",
    "description": "Lorem ipsum",
    "backdrop_path": "/kMe40oZHq3V.jpg"
}

###

POST {{url}}/peliculas/alquilar/
Content-Type: application/json

{
    "UsuarioId": 41,
    "PeliculaId": 1
}

###

POST {{url}}/usuarios/registro/
Content-Type: application/json

{
    "email": "pepe@gmail.com",
    "password": "1234"
}
###

GET {{url}}/peliculas/titulo/Enola/

###

GET {{url}}/peliculas/2
###

GET {{url}}/usuarios/perfil
Content-Type: application/json
Authorization: {{token}}


